amp: False
device: cuda:0
attack_label_trans: all2one
attack_target:
client_optimizer: sgd
dataset: gtsrb
dataset_path: ../data
frequency_save: 50
batch_size: 128
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: preactresnet18
pratio: 0.8
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
attack: sig
epochs: 100
sig_delta: 60
sig_f: 6