device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
log_file_name:
data_root: 'data/'

dataset: 'tiny'
num_classes: 
input_height: 
input_width:
input_channel:
val_frac: 0.1

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: ReduceLROnPlateau

poison_rate: 0.1
target_type: 'all2one'
target_label: 0

model: 'preactresnet18'
seed: 33333
index: 

ratio: 0.05

