---
dataset: gtsrb
dataset_path: "/home/lupang/Documents/data"
num_classes: 43
adv_dataset_dir: "./adv_datasets"
adv_model_path: "./adv_models/gtsrb_model_resnet18_comp.pth"
size: [32, 32, 3]  # [height, weight, channel]
normalization_layer: null
loader:
  batch_size: 512
  num_workers: 4
  pin_memory: True
pgd:
  eps: 16
  alpha: 1.5
  steps: 100
  max_pixel: 255